---
- hosts: localhost
  become: yes
  gather_facts: False
  tasks:
    - name: git pentest tools
      git:
        repo: https://github.com/ANK1036Official/Git_Pentesting_Toolkit.git
        dest: /home/vagrant/abc
        update: yes
        version: master
